title: Lingxi Liu AOS C204 Fall2024 Final Project
description: Steam User Preference and Game Recommendation using Simple Decision Tree Classifier
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-merlot
