title: Steam User Preference and Game Recommendation using Simple Decision Tree Classifier
description: AOS C204 Fall2024 Final Project
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-merlot
